---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "creative-narration.fullname" . }}-registrykey
  annotations:
  labels:
    {{- include "creative-narration.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
