# This skaffold is used to deploy components of the backend in a shared context, meaning each component will use the staging environment for all external services.
# All ingresses are disabled for these deployments to avoid rate limiting. Users can access their deployments though a port-foreword that's automatically created once deployed.
# Examples:
# skaffold run --tail
# https://skaffold.dev/docs/install/
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: creativenarration
profiles:
  - name: creativenarration
    activation: [{}] # Set as default profile
    build:
      local:
        push: true
      tagPolicy:
        gitCommit: {}
      artifacts:
        - &build
          image: ghcr.io/dmanias/creativenarration
          context: .
          docker:
            target: development
            dockerfile: deployments/Dockerfile
    deploy:
      kubeContext: ""
      helm:
        releases:
          - &deploy
            name: creativenarration
            chartPath: deployments/chart
            namespace: creativenarration
            createNamespace: true
            wait: false
            valuesFiles:
              - deployments/chart/values.yaml
            setValues: {}
            setValueTemplates:
              imageCredentials:
                username: "{{.GH_USERNAME}}"
                password: "{{.GH_TOKEN}}"
              image:
                tag: "{{.IMAGE_TAG}}"
    portForward:
    - &port-forward-http
      resourceType: service
      resourceName: creativenarration-creative-narration
      namespace: creativenarration
      port: 80
      localPort: 3000
#    - &port-forward-debug
#      resourceType: deployment
#      resourceName: creativenarration-creative-narration
#      namespace: creativenarration
#      port: 4000
#      localPort: 4000
